blank_issues_enabled: true
contact_links:
    - name: DM Sqaaakoi on Discord
      url: https://discord.com/users/259558259491340288
      about: If you need help regarding my Vencord fork, you can DM me. Responses are not guaranteed.
