name: Build DevBuild
on:
    push:
        paths:
            - .github/workflows/build.yml
            - src/**
            - browser/**
            - scripts/build/**
            - package.json
            - pnpm-lock.yaml
env:
    FORCE_COLOR: true

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm build --standalone

            - name: Generate plugin list
              run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

            - name: Clean up obsolete files
              run: |
                  rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

            - name: Get some values needed for the release
              id: release_values
              run: |
                  echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
                  echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
                  echo "commit_ref=$(git rev-parse HEAD)" >> $GITHUB_ENV
                  echo "build_timestamp=$(date +%s)" >> $GITHUB_ENV

            - name: Upload DevBuild as release
              if: ${{ github.repository == 'Sqaaakoi/Vencord' }}
              run: |
                  gh release create "${BUILD_TIMESTAMP}+${BRANCH_NAME}" -d --target "${COMMIT_REF}" ${RELEASE_TYPE} --title "DevBuild $RELEASE_TAG $BRANCH_NAME"
                  gh release upload "${BUILD_TIMESTAMP}+${BRANCH_NAME}" --clobber dist/*
                  gh release edit "${BUILD_TIMESTAMP}+${BRANCH_NAME}" --draft=false ${RELEASE_TYPE}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ env.release_tag }}
                  BRANCH_NAME: ${{ env.branch_name }}
                  COMMIT_REF: ${{ env.commit_ref }}
                  BUILD_TIMESTAMP: ${{ env.build_timestamp }}
                  RELEASE_TYPE: ${{ github.ref == 'refs/heads/sqaaakoi-stable' && '--latest' || '--prerelease' }}
