name: Test Patches
on:
    push:
        branches:
            - sqaaakoi-stable-v2
        paths:
            - .github/workflows/reportBrokenPlugins.yml
            - src/**
            - browser/**
            - scripts/build/**
            - package.json
            - pnpm-lock.yaml
    workflow_dispatch:
        inputs:
            discord_branch:
                type: choice
                description: "Discord Branch to test patches on"
                options:
                    - both
                    - stable
                    - canary
                default: both
    schedule:
        # Every 6 hours
        - cron: 0 0,6,12,18 * * *
    # schedule:
    #   # Every day at midnight
    #   - cron: 0 0 * * *

jobs:
    TestPlugins:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: 'recursive'

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile

            - name: Install Google Chrome
              id: setup-chrome
              uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce
              with:
                  chrome-version: stable

            - name: Build Vencord Reporter Version
              run: pnpm buildReporter

            - name: Run Reporter
              timeout-minutes: 10
              run: |
                  export PATH="$PWD/node_modules/.bin:$PATH"
                  export CHROMIUM_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
                  export WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  export COMMIT_HASH=$(git rev-parse HEAD)
                  export BRANCH_NAME=${GITHUB_REF#refs/heads/}

                  git restore --source sqaaakoi-stable-v2 -- scripts/generateReport.ts
                  esbuild scripts/generateReport.ts > dist/report.mjs

                  stable_output_file=$(mktemp)
                  canary_output_file=$(mktemp)

                  pids=""

                  branch="${{ inputs.discord_branch }}"
                  if [[ "${{ github.event_name }}" = "schedule" ]]; then
                    branch="both"
                  fi

                  if [[ "$branch" = "both" || "$branch" = "stable" ]]; then
                    node dist/report.mjs > "$stable_output_file" &
                    pids+=" $!"
                  fi

                  if [[ "$branch" = "both" || "$branch" = "canary" ]]; then
                    USE_CANARY=true node dist/report.mjs > "$canary_output_file" &
                    pids+=" $!"
                  fi

                  exit_code=0
                  for pid in $pids; do
                      if ! wait "$pid"; then
                        exit_code=1
                      fi
                  done

                  cat "$stable_output_file" "$canary_output_file" >> $GITHUB_STEP_SUMMARY
                  exit $exit_code
              env:
                  WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
                  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
