name: Test Patches
on:
    push:
        branches:
            - sqaaakoi-stable-v2
        paths:
            - .github/workflows/reportBrokenPlugins.yml
            - src/**
            - browser/**
            - scripts/build/**
            - package.json
            - pnpm-lock.yaml
    workflow_dispatch:
        # inputs:
        #         branch:
        #             type: string
        #             required: true
        #             description: the branch to run the reporter on
        #             default: sqaaakoi-stable-v2
    schedule:
        # Every 6 hours
        - cron: 0 0,6,12,18 * * *

jobs:
    TestPlugins:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              if: ${{ github.event_name != 'workflow_dispatch' }}
              with:
                  submodules: 'recursive'

            - uses: actions/checkout@v4
              if: ${{ github.event_name == 'workflow_dispatch' }}
              with:
                  ref: "${{ inputs.branch }}"
                  submodules: 'recursive'

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile

            - name: Install Google Chrome
              id: setup-chrome
              uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce
              with:
                  chrome-version: stable

            - name: Build Vencord Reporter Version
              run: pnpm buildReporter

            - name: Create Report
              timeout-minutes: 10
              run: |
                  export PATH="$PWD/node_modules/.bin:$PATH"
                  export CHROMIUM_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
                  export WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  export COMMIT_HASH=$(git rev-parse HEAD)
                  export BRANCH_NAME=${GITHUB_REF#refs/heads/}

                  git restore --source sqaaakoi-stable-v2 -- scripts/generateReport.ts
                  esbuild scripts/generateReport.ts > dist/report.mjs
                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
              env:
                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

            - name: Create Report (Canary)
              timeout-minutes: 10
              if: success() || failure() # even run if previous one failed
              run: |
                  export PATH="$PWD/node_modules/.bin:$PATH"
                  export CHROMIUM_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
                  export USE_CANARY=true
                  export WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                  export COMMIT_HASH=$(git rev-parse HEAD)
                  export BRANCH_NAME=${GITHUB_REF#refs/heads/}

                  git restore --source sqaaakoi-stable-v2 -- scripts/generateReport.ts
                  esbuild scripts/generateReport.ts > dist/report.mjs
                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
              env:
                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
